# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b7b891c8b3ea363f24be9e4e959b3aca0037fcd381c72c814533cff00b31eb119efa0e24da0001c4cf2012b029005f8b2677ce53179274917cb66267a708d8

test:
  secret_key_base: 399230fb73b39fe185ea4c54272c1f6eb1a6c7694da3fa0a7e495784f219a2ff8373d00ef7e68b6279da80ba51f13f381bcf972db3a244931ac4596a82bbf48c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
